version: '3.8'

services:

  db:
    container_name: eho-eho-db
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./containers/mysql/init:/docker-entrypoint-initdb.d:ro
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    #ヘルスチェックを使ってmysqlが作成されてからFastAPIが起動するようにする
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  backend:
    container_name: eho-eho-backend
    build:
      context: .
      dockerfile: containers/fastapi/Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: eho-eho-frontend
    build:
      context: .
      dockerfile: containers/react/Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - FAST_REFRESH=true
      - CHOKIDAR_USE_POLLING=true
    command: npm run dev -- --host 0.0.0.0

volumes:
  mysql_data:
    driver: local
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind

