services:

  db:
    container_name: eho-eho-db
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./containers/mysql/init:/docker-entrypoint-initdb.d:ro
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    #ヘルスチェックを使ってmysqlが作成されてからFastAPIが起動するようにする
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  backend:
    container_name: eho-eho-backend
    build:
      context: .
      dockerfile: containers/fastapi/Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/app:/app
      - backend_venv:/app/.venv
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,ja
      - LT_DISABLE_WEB_UI=true
      - LT_UPDATE_MODELS=false
      - HOME=/home/libretranslate
    volumes:
      - ./translate-data/libretranslate:/home/libretranslate/.local/share/libretranslate
      - ./translate-data/argos:/home/libretranslate/.local/share/argos-translate
      - ./init.sh:/init.sh
    command: ["sh", "/init.sh"]
    restart: unless-stopped

  frontend:
    container_name: eho-eho-frontend
    build:
      context: .
      dockerfile: containers/react/Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - FAST_REFRESH=true
      - CHOKIDAR_USE_POLLING=true
    command: npm run dev -- --host 0.0.0.0

volumes:
  libretranslate_data:
  libretranslate_argos:
  backend_venv:
  node_modules:
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind

