version: '3.8'

services:

  db:
    container_name: eho-eho-db
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./containers/mysql/init:/docker-entrypoint-initdb.d
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    
    #ヘルスチェックを使ってmysqlが作成されてからFastAPIが起動するようにする
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/mydb
    depends_on:
      - db

